branch-defaults:
  dev-master:
    environment: Rdyappstaging-env
    group_suffix: null
  main:
    environment: Rdyapp-env
  master:
    environment: Rdyapp-env
environment-defaults:
  Rdyapp-env:
    branch: master
    repository: null
  Rdyappstaging-env:
    branch: null
    repository: null
global:
  application_name: RDY App
  branch: null
  default_ec2_keyname: aws-rdy
  default_platform: 64bit Amazon Linux 2 v3.3.1 running PHP 8.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
