branch-defaults:
  dev-master:
    environment: Rdyapp-env
environment-defaults:
  Rdyapp-env:
    branch: null
    repository: null
global:
  application_name: RDY App
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2 v3.3.1 running PHP 8.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: production
  sc: git
  workspace_type: Application
